"""empty message

Revision ID: 09add9431466
Revises: 
Create Date: 2018-05-28 20:18:44.325752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09add9431466'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('dirc', sa.String(length=64), nullable=True),
    sa.Column('intr', sa.String(length=128), nullable=True),
    sa.Column('tel', sa.String(length=11), nullable=True),
    sa.Column('addr', sa.String(length=64), nullable=True),
    sa.Column('is_rest', sa.Boolean(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tel')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.Column('user_msg', sa.String(length=128), nullable=True),
    sa.Column('doc_msg', sa.String(length=128), nullable=True),
    sa.Column('user_name', sa.String(length=8), nullable=True),
    sa.Column('doc_name', sa.String(length=8), nullable=True),
    sa.Column('user_time', sa.DateTime(), nullable=True),
    sa.Column('doc_time', sa.DateTime(), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('sort', sa.String(length=8), nullable=True),
    sa.Column('guige', sa.String(length=64), nullable=True),
    sa.Column('come_sourse', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('input_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_name'), 'stores', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('tel', sa.String(length=11), nullable=True),
    sa.Column('sex', sa.String(length=8), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('tel')
    )
    op.create_table('queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=8), nullable=True),
    sa.Column('sex', sa.String(length=8), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('addr', sa.String(length=64), nullable=True),
    sa.Column('tel', sa.String(length=11), nullable=True),
    sa.Column('desc', sa.String(length=140), nullable=True),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.Column('doc_desc', sa.String(length=128), nullable=True),
    sa.Column('treat', sa.String(length=128), nullable=True),
    sa.Column('for_time1', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('doctor_name', sa.String(length=64), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tel')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue')
    op.drop_table('user')
    op.drop_index(op.f('ix_stores_name'), table_name='stores')
    op.drop_table('stores')
    op.drop_table('message')
    op.drop_table('doctor')
    op.drop_table('admins')
    # ### end Alembic commands ###
